// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfxMEtwXZUdDOx4Qot6LAIe8Zb-l2GvtE',
    appId: '1:853700695890:web:0935c7585411478a4a8c8b',
    messagingSenderId: '853700695890',
    projectId: 'sound-slice',
    authDomain: 'sound-slice.firebaseapp.com',
    storageBucket: 'sound-slice.appspot.com',
    measurementId: 'G-9TN0VL9WDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkk9h743XHC0qDrEwysGO3yQL9SZequyk',
    appId: '1:853700695890:android:da025f141f7d600a4a8c8b',
    messagingSenderId: '853700695890',
    projectId: 'sound-slice',
    storageBucket: 'sound-slice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcrcz7ifLNHwbn4z5_enCGlGZIbMNXsOQ',
    appId: '1:853700695890:ios:bd4be5f43b8361744a8c8b',
    messagingSenderId: '853700695890',
    projectId: 'sound-slice',
    storageBucket: 'sound-slice.appspot.com',
    iosClientId: '853700695890-i10c3djrnlctmofo2jv63memhajucevp.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundSlice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcrcz7ifLNHwbn4z5_enCGlGZIbMNXsOQ',
    appId: '1:853700695890:ios:bd4be5f43b8361744a8c8b',
    messagingSenderId: '853700695890',
    projectId: 'sound-slice',
    storageBucket: 'sound-slice.appspot.com',
    iosClientId: '853700695890-i10c3djrnlctmofo2jv63memhajucevp.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundSlice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfxMEtwXZUdDOx4Qot6LAIe8Zb-l2GvtE',
    appId: '1:853700695890:web:d98ca026e7e225a44a8c8b',
    messagingSenderId: '853700695890',
    projectId: 'sound-slice',
    authDomain: 'sound-slice.firebaseapp.com',
    storageBucket: 'sound-slice.appspot.com',
    measurementId: 'G-FN2265XHHR',
  );
}
